[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_mplxcore_q4_25 = "CzPkGKrcPBnPrXNMPZ72JC3qhxWnhgTsBAoxwHYHyq2j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/david/.config/solana/id.json"

[test]
startup_wait = 15000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""